#!/bin/bash
#A little script to randomize your mac address
#Coded by GUNN4R, 1 Aug 2014
function manual () {
  echo -e "Usage:\\nchmac -r <adapter>"
  echo -e "\\n -r -- assign a random mac address"
  echo "Example:"
  echo "chmac.sh -r wlan0  -- this sets the mac address to be random"
  exit
}

if [ "$#" -eq 0 ]
then
  echo "NOT ENOUGH ARGUMENTS!"
  manual
fi

if [ "$1" = "-r" ]
then 
  #generate random mac address
  newmac="$(head -c 500 /dev/urandom | tr -dc 'A-F0-9' | fold -w 2 | tr '\n' ':' | head -c 17)"
  echo "Assigning new mac address:" $newmac
  #apply random mac address to specified interface
  sudo ifconfig $2 down
  sudo ifconfig $2 hw ether $newmac
  sudo ifconfig $2 up
  #display info about interface
  ifconfig
else
  echo "WAT!? :" $1
  manual
fi
